[project]
name = "hidef-transmed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "setuptools<75",
    "leidenalg>=0.11.0",
    "louvain>=0.7.1",
    "networkx>=3.6.1",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "hidef>=1.1.5",
    "pip>=26.1",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.9",
    "graphviz>=0.21",
    "pygraphviz>=1.14",
    "statsmodels>=0.14.6",
    "gseapy>=1.2.1",
]
